config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists do
    resources :bookmarks
  end
  resources :movies, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_movie, only: %i[new create]

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.movie = @movie
    @bookmark.save
  end

  private

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create

  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movie = Movie.find(params[:format])
  end

  def show
    @movie = Movie.find(params[:id])
    @list = List.find(params[:list_id])
  end

  private

  def movies_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/mouvies_helper.rb
module MouviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" >
  <h1 class="text-cinema" ><strong>Cinema</strong></h1>
  <%= image_tag "https://www.cheatcc.com/imagesfeatures/weeklyrant_actionadventure.jpg" ,  height: 400, width: "100%"%>
</div>
<div class="container">
  <h1 class="category-text" >Category of movies</h1>
  <div class="cards">
    <% @lists.each do |list| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.cheatcc.com/imagesfeatures/weeklyrant_actionadventure.jpg)">
        <%= link_to list.name, list_path(list)  %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="banner">
   <%= image_tag "https://www.cheatcc.com/imagesfeatures/weeklyrant_actionadventure.jpg" ,  height: 300, width: "70%"%>
</div>

<h1 class="category-name"><strong><%= @list.name.capitalize %></strong></h1>
<div class="row">
  <% @list.bookmarks.each do |item| %>
    <%# <div class="row-cols-1 row-cols-md-3 g-4"> %>
      <div class="col-3">
        <div class="card-product">
          <img src="<%=item.movie.poster_url  %>" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%= item.movie.title %></h5>
            <p class="card-text"> <%= item.movie.overview %></p>
            <%= link_to "Info", movies_path(item.movie) %>
          </div>
        </div>
      </div>
    <%# </div> %>
  <% end %>
</div>

app/views/movies/index.html.erb
<div class="container">
  <img src="<%= @movie.poster_url %>" alt="">
</div>

app/views/movies/show.html.erb
<div class="card" style="width: 18rem;">
  <img src=<%= @movie.poster_url %>  class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"><%= @movie.title %></h5>
    <p class="card-text"><%= @movie.overview %></p>
    <a href="#" class="btn btn-primary"></a>
  </div>
</div>